# References:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode10

script:
- set -o pipefail && xcodebuild -workspace Example/Quack.xcworkspace -scheme Quack-Example -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
